### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [2]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [17]:
###  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
a = np.zeros(10)  
print("An array of 10 Zeros: ") 
print(a)
b = np.ones(10)
print("An array of 10 ones : ") 
print(b)
c = np.full(10,5,dtype=float)
print("An array of 10 fives : ") 
print(c)



An array of 10 Zeros: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones : 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives : 
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [20]:
### Write a NumPy program to create an array of the integers from 30 to 70.
a = [i for i in range(30,71)]
arr = np.array(a,dtype=int)
print("Array of the integers from 30 to 70")
print(arr)

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [21]:
### Write a NumPy program to create an array of all the even integers from 10 to 50.
b = [i for i in range(10,50) if i%2 == 0]
arr1 = np.array(b,dtype=int)
print("Array of all the even integers from 10 to 50")
print(arr1)


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [22]:
###  Write a NumPy program to create a 3x3 identity matrix.
Identity_matrix = np.eye(3)
print("3x3 matrix: ")
print(Identity_matrix)

3x3 matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [26]:
### Write a NumPy program to generate a random number between 0 and 1
a = np.random.rand(1)
print("The random number between 0 and 1: ")
print(a)

The random number between 0 and 1: 
[0.66670654]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [27]:
## Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
b = np.random.randn(15)
print("15 random numbers from a standard notrmal distribution: ")
print(b)


15 random numbers from a standard notrmal distribution: 
[ 1.2076844  -0.47466918  0.27126601  0.22511299  0.62715813  0.35223226
 -1.28423531  0.14095776 -0.06219385 -0.01245859 -0.09743366  1.72261849
 -1.44920672 -1.45602557 -0.86944721]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [36]:
## Write a NumPy program to create a 3X4 array using and iterate over it.
c = [[10,11,12,13],[14,15,16,17],[18,19,20,21]]
arr = np.array(c)
print("Original array: ")
print(arr)
l = [element for i in arr for element in i]
print("Each element of the array is :")
print(l)


Original array: 
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is :
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [43]:
## Write a NumPy program to multiply the values ​​of two given vectors.
a = np.array([1,8,3,5]) # changing a list to a vector or array
print("Vector-1")
print(a)
b = np.array([10,1,4,10]) # changing a list to a vector or array 
print("Vector-2")
print(b)
product = list(map(lambda x,y:x*y,a,b)) # multiplyin two values of two given vectors using map and lambda functions.
print("Multiply the values of two said vectors: ")
print(np.array(product)) # changing a list to array or vector

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors: 
[10  8 12 50]


In [5]:
# method 2
a = np.array([1,8,3,5]) # changing a list to a vector or array
print("Vector-1")
print(a)
b = np.array([10,1,4,10]) # changing a list to a vector or array 
print("Vector-2")
print(b)
product = np.multiply(a,b)
print("Multiply the values of two said vectors : ")
print(product)

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors : 
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [52]:
### Write a NumPy program to reverse an array (first element becomes last).
arr = [i for i in range(12,38)]
a = np.array(arr)
print("Original array: ")
print(a)
reversed_array = a[-1::-1] # reversing an array using sliding technique
print("Reverse array:")
print(reversed_array)


Original array: 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [60]:
## Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
arr_1 = np.zeros((5,5),dtype=int)
new_arr = np.diag([1,2,3,4,5]) # we r using diag function to change diagonal values from zeros to 1,2,3,4,5.
print(new_arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [6]:
## Method 1
## Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

arr = np.array([[0, 1], [2, 3]])
print("Original array: ")
print(arr)

print("sum of all elemnts: ")
# Sum of all elements
total_sum = np.sum(arr)
print("Total sum:", total_sum)
print("sum of row elemnts")
# Sum of each row
row_sum = np.sum(arr, axis=1)
print("Row sum:", row_sum)
print("sum of column elemnts")
# Sum of each column
col_sum = np.sum(arr, axis=0)
print("Column sum:", col_sum)
        


Original array: 
[[0 1]
 [2 3]]
sum of all elemnts: 
Total sum: 6
sum of row elemnts
Row sum: [1 5]
sum of column elemnts
Column sum: [2 4]


In [7]:
## Method 2
## Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
arr = np.array([[0, 1], [2, 3]])
print("Original array: ")
print(arr)

print("sum of all elemnts: ")
# Sum of all elements
total_sum = np.sum(arr)
print("Total sum:", total_sum)
print("sum of row elemnts")
# Sum of each row
row_sum = [arr[0][0] + arr[0][1],arr[1][0] + arr[1][1]]
print("Row sum:", row_sum) 
print("sum of column elemnts")
# Sum of each column
col_sum = [arr[0][0] + arr[1][0],arr[0][1] + arr[1][1]]
print("Column sum:", col_sum)


Original array: 
[[0 1]
 [2 3]]
sum of all elemnts: 
Total sum: 6
sum of row elemnts
Row sum: [1, 5]
sum of column elemnts
Column sum: [2, 4]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [3]:
## Write a NumPy program to compute the inner product of two given vectors.
vector1 = np.array([4, 5])
vector2 = np.array([7,10])
print("Original Vectors: ")
print(vector1)
print(vector2)

# Compute the inner product of the two vectors
inner_product = np.dot(vector1, vector2)

print("Inner product of said vectors:")
print(inner_product)

Original Vectors: 
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [8]:
## Write a NumPy program to compute the inner product of two given vectors.
vector1 = np.array([4, 5])
vector2 = np.array([7,10])
print("Original Vectors: ")
print(vector1)
print(vector2)

# Compute the inner product of the two vectors
inner_product = np.multiply(vector1, vector2)

print("Inner product of said vectors:")
print(inner_product)

Original Vectors: 
[4 5]
[ 7 10]
Inner product of said vectors:
[28 50]
