### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


In [2]:
import numpy as np

###### 1. Write a NumPy program to find the missing data in a given array.

In [8]:
### Write a NumPy program to find the missing data in a given array.
arr = np.array([[3,3,np.nan,1],[10,12,10,9],[5,np.nan,1,np.nan]])
print("Original array: ")
print(arr)
mask = np.isnan(arr)
mask
print("Find the missing data of the said array: ")
print(mask)



Original array: 
[[ 3.  3. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
Find the missing data of the said array: 
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [65]:
### Write a NumPy program to check whether two arrays are equal (element wise) or not
arr = np.arange(0,6).reshape(2,3)
arr1 = np.arange(0,6).reshape(2,3)
if np.array_equal(arr,arr1):
    print("Both the arrays have equal elements")
else:
    print("Arrays are not equal")


Both the arrays have equal elements


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [28]:
## Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and
# last rows.
arr = np.random.randint(0,15,(4,4))
print("Original array : ")
print(arr)
new_arr = np.copy(arr)
new_arr[0], new_arr[-1] = new_arr[-1], new_arr[0]
new_arr1 = np.copy(new_arr)
new_arr1[-1], new_arr1[0] = arr[0], arr[-1]
print("New array after swapping first rows of the said array : ")
print(new_arr1)


Original array : 
[[ 1 13  2  9]
 [ 5  4  4  2]
 [ 0  7  1  9]
 [ 6 10  3  0]]
New array after swapping first rows of the said array : 
[[ 6 10  3  0]
 [ 5  4  4  2]
 [ 0  7  1  9]
 [ 1 13  2  9]]


In [62]:
## method 2
arr =np.arange(0,16).reshape(4,4)
print("Original array: ")
print(arr)
arr1 = np.copy(arr)
arr1[0] = arr[3]
arr2 = np.copy(arr1)
arr2[3] = arr[0]
print("New array after swapping first rows of the said array : ")
print(arr2)


Original array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New array after swapping first rows of the said array : 
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [31]:
### Write a NumPy program to convert a list and tuple into arrays.
# Convert a list into a NumPy array
list1 = [1, 2, 3, 4, 5]
array1 = np.array(list1)
print("Array from list:", array1)

# Convert a tuple into a NumPy array
tuple1 = (6, 7, 8, 9, 10)
array2 = np.array(tuple1)
print("Array from tuple:", array2)

Array from list: [1 2 3 4 5]
Array from tuple: [ 6  7  8  9 10]


###### 5. Write a NumPy program to find common values between two arrays.

In [38]:
### Write a NumPy program to find common values between two arrays

arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[4,3,2],[2,3,4],[5,6,7]])
for i in np.nditer(arr):
    for j in np.nditer(arr1):
        if i == j:
            print(j)

2
2
3
3
4
4
5
6


In [36]:
### Method 2
arr = np.random.randint(0,15,(3,3))
arr1 = np.random.randint(0,15,(3,3))
print(arr)
print(arr1)
for i in np.nditer(arr):
    for j in np.nditer(arr1):
        if i == j:
            print(j)

[[10 12  5]
 [13  9 11]
 [ 1  8 11]]
[[10 10  5]
 [ 9 10  2]
 [ 2  8  0]]
10
10
10
5
9
8


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [43]:
### Write a NumPy program to create a new shape to an array without changing its data.
arr = np.array([[1,2],[3,4],[4,5]])
print("Reshape 3x2: ")
print(arr)
arr1 = np.reshape(arr,(2,3))
print("Reshape 2x3: ")
print(arr1)

Reshape 3x2: 
[[1 2]
 [3 4]
 [4 5]]
Reshape 2x3: 
[[1 2 3]
 [4 4 5]]


In [44]:
#### Method2
arr = np.random.randint(0,20,(2,10))
print("Reshape 2x10: ")
print(arr)
arr1 = np.reshape(arr,(4,5))
print("Reshape 4x5: ")
print(arr1)

Reshape 2x10: 
[[11 17  4 19  6 18  7  2  6 13]
 [11 18 18 14 16  4  2 14  7  5]]
Reshape 4x5: 
[[11 17  4 19  6]
 [18  7  2  6 13]
 [11 18 18 14 16]
 [ 4  2 14  7  5]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [51]:
###  Write a NumPy program to count the frequency of unique values in numpy array
arr = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print("Original array: ")
print(arr)
unique_vals, counts = np.unique(arr, return_counts=True)
arr2 = np.array([unique_vals,counts])
print("Frequency of unique values of the said array: ")
print(arr2)

Original array: 
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array: 
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [52]:
### Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).
arr1 = np.array([[0,0,0],[1,2,3],[4,5,6]])
arr2 = np.array([10,11,12])
print("Array_1")
print(arr1)
print("Array_2")
print(arr2)
arr3 = arr1 + arr2
print("New array:")
print(arr3)

Array_1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array_2
[10 11 12]
New array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [53]:
### Write a NumPy program to extract all the elements of the second row from a given (4x4) array.
arr = np.arange(0,16)
arr1 = np.reshape(arr,(4,4))
print("Original array")
print(arr1)
arr2 = arr1[1:2,:]
print("Extracted data : second row ")
print(arr2)


Original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted data : second row 
[[4 5 6 7]]


In [56]:
## Another way
import numpy as np
arr_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arr_data)
print("\nExtracted data: Second row")
print(arr_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [60]:
## Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.
arr = np.arange(0,16).reshape(4,4)
print("Original array: ")
print(arr)
arr1 = np.array([arr[0,2:4],arr[1,2:4]])
print("Extracted data: Third and fourth elements of the first and second rows")
print(arr1)

Original array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [57]:
### Write a NumPy program to get the dates of yesterday, today and tomorrow.
import datetime
w
# Get today's date
today = np.datetime64(datetime.date.today())

# Get yesterday's date
yesterday = np.datetime64(datetime.date.today() - datetime.timedelta(days=1))

# Get tomorrow's date
tomorrow = np.datetime64(datetime.date.today() + datetime.timedelta(days=1))

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-02-19
Today: 2023-02-20
Tomorrow: 2023-02-21


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [3]:
## Write a NumPy program to find the first Monday in May 2017.
# Set the date to May 2017
date = np.datetime64('2017-05')

# Find the first Monday in May 2017
first_monday = np.busday_offset(date, 0, roll='forward', weekmask='Mon')
# the function is being used to calculate the first Monday following the given date.
# The date parameter specifies the starting date, 0 specifies the number of business days to offset (i.e., zero days), 
# and roll='forward' indicates that if the starting date is not a business day, the function should return the next business day. 
#The weekmask='Mon' parameter specifies that only Mondays are considered business days.

# Print the result
print("First Monday in May 2017 is:")
print(first_monday)

First Monday in May 2017 is:
2017-05-01
